import Head from 'next/head';
import Features from '../components/Features';
import GetStarted from '../components/GetStarted';
import Hero from '../components/Hero';
import StayProductive from '../components/StayProductive';
import Testimonial from '../components/Testimonial';

export default function Home() {
	return (
		<>
			<Head>
				<title>Fylo Landing Page</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

      <Hero/>
      <Features/>
      <StayProductive/>
      <Testimonial/>
      <GetStarted/>
		</>
	);
}
